export const ADD_PRODUCT = 'ADD_PRODUCT';
export const USER_LOGIN_PROCESS = 'USER_LOGIN_PROCESS';
export const IS_USER_REGISTER = 'IS_USER_REGISTER'
export const IS_USER_UPDATED = 'IS_USER_UPDATED'

export const SET_OPEN_DELETE_CONFIRM_DIALOG = 'SET_OPEN_DELETE_CONFIRM_DIALOG'

export const IS_EMPLOYEE_AUTHENTICATED = 'IS_EMPLOYEE_AUTHENTICATED';
export const SET_USER_DATA = 'SET_USER_DATA';
export const IS_USER_AUTHENTICATION_UPDATED = 'IS_USER_AUTHENTICATION_UPDATED'